### ISSUE TITLE
java.nio.file.NoSuchFileException occurred.

### ISSUE THREAD

**Issue by crossroad0201** [crossroad0201/flyway-awslambda#1]
```
TART RequestId: c3d89469-b5ce-11e6-b14e-e103d2c39e6b Version: $LATEST
Flyway migration start. by ObjectCreated:Put s3://l*******/flyway/V1__create_table.sql
java.nio.file.NoSuchFileException: /tmp/c3d89469-b5ce-11e6-b14e-e103d2c39e6b/flyway/V1__create_table.sql
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
at java.nio.file.Files.newOutputStream(Files.java:216)
at java.nio.file.Files.copy(Files.java:3016)
at crossroad0201.aws.flywaylambda.S3EventMigrationHandler.createSqlFile$1(S3EventMigrationHandler.scala:78)
at crossroad0201.aws.flywaylambda.S3EventMigrationHandler.deployInternal$1(S3EventMigrationHandler.scala:90)
at crossroad0201.aws.flywaylambda.S3EventMigrationHandler.$anonfun$migrate$1(S3EventMigrationHandler.scala:103)
at scala.util.Try$.apply(Try.scala:209)
at crossroad0201.aws.flywaylambda.S3EventMigrationHandler.deployFlywayResources$1(S3EventMigrationHandler.scala:58)
at crossroad0201.aws.flywaylambda.S3EventMigrationHandler.migrate(S3EventMigrationHandler.scala:142)
at crossroad0201.aws.flywaylambda.S3EventMigrationHandler.handleRequest(S3EventMigrationHandler.scala:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at lambdainternal.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:456)
at lambdainternal.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:375)
at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:1140)
at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:285)
at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:57)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:94)
END RequestId: c3d89469-b5ce-11e6-b14e-e103d2c39e6b
REPORT RequestId: c3d89469-b5ce-11e6-b14e-e103d2c39e6b	Duration: 11836.20 ms	Billed Duration: 11900 ms Memory Size: 1536 MB	Max Memory Used: 115 MB	
```

**Comment by crossroad0201** [comment]
### Cause

Temporary directory `/tmp/xxxxx/flyway` does not exists at create SQL file.

### Fix

Sort S3 objects by key accending.
Create directory before create SQL file.
